name: Cardona Bot – Resumen diario
on:
  schedule:
    # 20:10 UTC == 16:10 NY (cierre)
    - cron: "10 20 * * 1-5"
  workflow_dispatch:
jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install --upgrade pip yfinance pandas requests
      - name: Enviar resumen único
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python cardona_summary.py