name: summary
on:
  schedule:
    - cron: "10 21 * * 1-5"       # 17:10 NY aprox.
  workflow_dispatch:
jobs:
  diario:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: { python-version: "3.11" }
      - name: Install deps
        run: pip install --upgrade pip yfinance pandas requests
      - name: Run summary
        run: python cardona_summary.py
