name: summary
on:
  schedule:
    # 21:10 UTC ≈ 17:10 NY – después del cierre (16:00)
    - cron: "10 21 * * 1-5"
  workflow_dispatch: {}   # permite lanzarlo manualmente

jobs:
  enviar-resumen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip yfinance pandas telegram requests

      - name: Enviar resumen único
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python cardona_summary.py
