name: Cardona Bot Diario

on:
  schedule:
    - cron: '31 13 * * 1-5'
    - cron: '0 14 * * 1-5'
    - cron: '0 16 * * 1-5'
    - cron: '0 18 * * 1-5'
    - cron: '45 19 * * 1-5'

  workflow_dispatch:

jobs:
  ejecutar-bot:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar bot Cardona
        run: python main.py
